### ISSUE TITLE
Implement way to set the url of the machine running the ROS server

### ISSUE THREAD

**Issue by mayshukla** [team510nm/spearMCT#4]
Currently, the url is hard-coded in modules.json.

It would be better to be able to set this through a command-line argument or possibly through the gui.

**Comment by M0RGaming** [comment]
Resolved in #7 

The URL is now provided via a command-line argument while calling `npm start`. If no URL is provided, the server will now run in offline mode, which was previously accessed by `npm test`.

Syntax to start the server:
`npm start [Websocket URL (Optional)]`
