### ISSUE TITLE
Error when installing ImportExport plugin

### ISSUE THREAD

**Issue by mayshukla** [team510nm/spearMCT#5]
I'm getting this error in the console when I open http://localhost:8080/ in my browser.

Note: I'm on the update-openmct-ryan branch so maybe I broke something when I updated the version of openmct.

```Uncaught Error: Cannot register bundle with duplicate path
    register http://localhost:8080/node_modules/openmct/dist/openmct.js:308
    o http://localhost:8080/node_modules/openmct/dist/openmct.js:329
    install http://localhost:8080/node_modules/openmct/dist/openmct.js:308
    <anonymous> http://localhost:8080/index.html:32
platform/import-export:308:65541
    register http://localhost:8080/node_modules/openmct/dist/openmct.js:308
    o http://localhost:8080/node_modules/openmct/dist/openmct.js:329
    install http://localhost:8080/node_modules/openmct/dist/openmct.js:308
    <anonymous> http://localhost:8080/index.html:32
```

**Comment by M0RGaming** [comment]
I believe that I was getting a similar issue as well before I hardcoded the OpenMCT version to be what it was. I'll take another look at it tomorrow and see if I can't update the OpenMCT version while keeping errors to a minimum, as well as get back into the project a bit.

**Comment by M0RGaming** [comment]
Import Export is now being provided automatically by the base openmct file. Changes have been made in #6 to resolve this issue.
